# Generated by Django 2.1.11 on 2023-02-04 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('currency_code', models.CharField(max_length=5)),
                ('image_url', models.TextField()),
                ('url_site', models.TextField()),
                ('marketplace', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
